# Generated by Django 5.1.7 on 2025-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Fusion', '0002_rename_product_image_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shelling_price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vender',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
