# Generated by Django 5.1.7 on 2025-03-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Fusion', '0003_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='catagory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='shelling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='vender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
