# Generated by Django 5.1.7 on 2025-03-23 01:42

import Shop_Fusion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Fusion', '0004_rename_category_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=Shop_Fusion.models.Getfilename),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=Shop_Fusion.models.Getfilename),
        ),
    ]
