# Generated by Django 5.1.7 on 2025-03-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Fusion', '0005_alter_catagory_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='vender',
            field=models.CharField(max_length=255),
        ),
    ]
